// FAQ data — canonical source for the public /faq page.
// Content derived from section 7 of the Hearth KB (HEARTH_KB_paste_v1.1.md,
// the file stays gitignored as operational ops). Consumed via tr.faqPage.categories.
// Kept in a separate module so lib/translations.ts stays readable.

export type FAQItem = { question: string; answer: string };
export type FAQCategory = {
  slug: "about-us" | "services" | "service-area" | "financing";
  label: string;
  items: FAQItem[];
};

export const FAQ_CATEGORIES_EN: FAQCategory[] = [
  {
    slug: "about-us",
    label: "About Us",
    items: [
      { question: "What does Smooth Fence USA do?", answer: "Smooth Fence USA provides fence installation, fence repair, and free on-site estimates for residential projects." },
      { question: "Are you licensed and insured?", answer: "Yes. Smooth Fence USA is licensed and insured." },
      { question: "What makes Smooth Fence USA different?", answer: "Customers work directly with the owner, no subcontractors, clear pricing, and clean professional work built for Florida weather." },
      { question: "Do you offer a warranty?", answer: "Yes. Smooth Fence USA offers a 5-year workmanship warranty on every residential installation." },
      { question: "What does the workmanship warranty cover?", answer: "Issues caused by installation errors: panels loosening from improper fastening, posts failing due to incorrect setting, gates misaligned at install, and similar installation-related defects. Full terms in the written warranty delivered with the project." },
      { question: "What does the warranty NOT cover?", answer: "Storm damage, hurricanes, flooding, vehicle or tree impact, vandalism, lack of maintenance, normal wear and tear, sun-fade discoloration, or third-party modifications after installation." },
      { question: "Is there a manufacturer warranty on materials?", answer: "Yes. Vinyl typically carries a manufacturer limited lifetime warranty. Aluminum typically carries 10–20 years. Wood and chain-link vary by product." },
      { question: "Is the warranty transferable?", answer: "The workmanship warranty is generally non-transferable and applies to the original homeowner. Manufacturer warranties vary." },
      { question: "Is the warranty provided in writing?", answer: "Yes, full details in the written quote and contract." },
      { question: "How do I file a warranty claim?", answer: "Call (386) 403-9460 or email info@smoothfenceusa.com with photos and a description. Federico will schedule an inspection." },
      { question: "What is your response time?", answer: "Short questions, same business day." },
      { question: "What are your business hours?", answer: "Monday through Saturday, 8:00 AM to 6:00 PM." },
      { question: "Can I reach you by call or text?", answer: "Yes, both." },
      { question: "What is your contact info?", answer: "Phone (386) 403-9460. Email info@smoothfenceusa.com." },
    ],
  },
  {
    slug: "services",
    label: "Services Offered",
    items: [
      { question: "What types of fences do you install?", answer: "We install vinyl, aluminum, chain-link, and wood fences." },
      { question: "Do you offer fence repair?", answer: "Yes. We repair damaged sections, leaning posts, broken panels, gate issues, and some storm-damaged fences." },
      { question: "Are fences customizable?", answer: "Yes. Customized by material, layout, privacy, and style." },
      { question: "What's the best material for Florida?", answer: "Depends on the project. Vinyl = low maintenance + privacy. Aluminum = durability + visibility. Chain-link = cost-effective. Wood = classic look." },
      { question: "What vinyl styles are available?", answer: "Full privacy, privacy with decorative top, semi-privacy, and picket." },
      { question: "Is aluminum good for pools?", answer: "Yes. Safety, visibility, and clean look." },
      { question: "Do you install wood fences?", answer: "Yes, standard option." },
      { question: "Can you repair only part of the fence?", answer: "Yes when damage is limited. Widespread structural issues may be better to replace." },
      { question: "Do you handle storm-damaged fences?", answer: "Yes. We inspect and decide repair vs replacement." },
      { question: "Do you remove the old fence?", answer: "Yes, can be included in the quote when needed." },
      { question: "Can you match my existing fence?", answer: "Sometimes, depending on material, style, color, age, and current product availability." },
      { question: "What gate types and sizes do you offer?", answer: "Standard walk-gate sizes are 4 ft and 5 ft wide. We also build custom-size gates to whatever opening you need, in any material. Custom gates add fabrication, installation, and transportation charges on top of the standard price." },
      { question: "Can gates be automated?", answer: "No. Smooth Fence USA does not offer gate automation. All our gates are manually operated. If you need automation, you can coordinate that separately with an access-control installer after we complete the gate." },
      { question: "What hardware do you use?", answer: "Heavy-duty galvanized or stainless-steel hinges and latches rated for the gate's weight and material. We don't commit to a specific brand — we choose what works best for each project. If you have a brand preference, we're open to it at your request." },
      { question: "How do you handle pool gate safety?", answer: "Florida pool code typically requires self-closing and self-latching hardware with the latch at least 54 inches above grade, and gates swinging outward from the pool. We install pool-code-compliant hardware on request." },
      { question: "Do you install access control (keypads, card readers)?", answer: "We install standard keyed locks and manual latches only. For keypad, intercom, or card readers, customers coordinate with a separate access-control provider." },
      { question: "Do you set posts in concrete?", answer: "Depends on project, soil, local code, and fence type. Goal is always stable and long-lasting." },
      { question: "How do fences hold up to Florida weather?", answer: "We choose materials and methods designed for heat, humidity, storms, and coastal conditions." },
      { question: "What is virgin vinyl?", answer: "New, non-recycled vinyl, preferred for consistency and long-term durability." },
      { question: "Routed vs bracket-mounted vinyl — what's the difference?", answer: "Routed inserts the rails directly into the posts for a cleaner look. Bracket-mounted uses external connectors." },
      { question: "What post caps are available?", answer: "Flat, pyramid, gothic, New England-style, solar-light caps." },
    ],
  },
  {
    slug: "service-area",
    label: "Service Area & Estimates",
    items: [
      { question: "What areas do you serve?", answer: "Palm Coast, Flagler County, Volusia County, St. Johns County, Duval County, and Putnam County. Nearby areas may be possible depending on the address." },
      { question: "Are estimates free?", answer: "Yes. Free, no-obligation on-site estimates." },
      { question: "What's the fastest way to get a quote?", answer: "Use the instant estimator at smoothfenceusa.com/estimator, then schedule a free on-site visit to confirm." },
      { question: "How long does installation take?", answer: "Most residential projects are completed in 1 to 3 days, depending on size, terrain, weather, access, and material." },
      { question: "What affects the price of a fence?", answer: "Material, height, linear footage, number of gates, terrain, layout, old fence removal, and any special site conditions. Firm pricing only after the free on-site visit." },
      { question: "Do you help with HOA approval?", answer: "Yes, we help review HOA requirements and provide supporting details." },
      { question: "Who submits the HOA application?", answer: "In most cases the homeowner. We provide the info needed." },
      { question: "Do projects require permits?", answer: "Some projects require city/county permits, some do not. Depends on location and scope. We guide through the steps when required." },
      { question: "How do you handle property lines and easements?", answer: "We plan layouts with them in mind, but final boundary determinations come from a survey or the proper authority." },
      { question: "What should I prepare before install day?", answer: "Property access clear, work area cleared, pets secured, any HOA/permit items underway if needed." },
    ],
  },
  {
    slug: "financing",
    label: "Financing & Pricing",
    items: [
      { question: "Do you offer financing?", answer: "Yes, through Hearth for qualified customers." },
      { question: "Does applying affect my credit score?", answer: "No, Hearth uses a soft-pull pre-qualification." },
      { question: "Can I pay in monthly payments?", answer: "Yes, qualified customers can break the project into monthly payments." },
      { question: "What types of financing are available?", answer: "Personal loans, HELOCs, promotional credit card offers." },
      { question: "Is 0% financing available?", answer: "Some qualified homeowners get promotional 0% introductory APR cards, subject to lender terms." },
      { question: "How fast can financing funds arrive?", answer: "As fast as 24 hours in some cases once approved." },
      { question: "What's the minimum FICO score?", answer: "Hearth states as low as 550, but approval depends on lender and applicant." },
      { question: "Do I need an estimate before applying for financing?", answer: "Yes, estimate first, then review financing." },
    ],
  },
];

export const FAQ_CATEGORIES_ES: FAQCategory[] = [
  {
    slug: "about-us",
    label: "Sobre Nosotros",
    items: [
      { question: "¿Qué hace Smooth Fence USA?", answer: "Smooth Fence USA hace instalación de cercas, reparación de cercas, y estimados gratuitos en el sitio para proyectos residenciales." },
      { question: "¿Tienen licencia y seguro?", answer: "Sí." },
      { question: "¿Qué los diferencia?", answer: "El cliente trata directo con el dueño, sin subcontratistas, precios claros, y trabajo limpio y profesional preparado para el clima de Florida." },
      { question: "¿Ofrecen garantía?", answer: "Sí. 5 años de garantía de mano de obra en toda instalación residencial." },
      { question: "¿Qué cubre la garantía de mano de obra?", answer: "Problemas de instalación: paneles sueltos por fijación incorrecta, postes que fallan por mal asentado, portones mal alineados de origen, y defectos similares de instalación. Términos completos en la garantía escrita que va con el proyecto." },
      { question: "¿Qué NO cubre la garantía?", answer: "Daños por tormenta, huracán, inundación, impacto de vehículo o árbol, vandalismo, falta de mantenimiento, desgaste normal, decoloración por sol, o modificaciones de terceros después de la instalación." },
      { question: "¿Hay garantía de fábrica en los materiales?", answer: "Sí. Vinyl suele traer limited lifetime. Aluminio 10–20 años. Madera y chain-link varían." },
      { question: "¿La garantía es transferible?", answer: "La garantía de mano de obra en general no es transferible, aplica al homeowner original. Las de fábrica varían." },
      { question: "¿La garantía va por escrito?", answer: "Sí, en la cotización escrita y el contrato." },
      { question: "¿Cómo reclamo la garantía?", answer: "Llamar al (386) 403-9460 o email a info@smoothfenceusa.com con fotos y descripción. Federico agenda la inspección." },
      { question: "¿En cuánto contestan?", answer: "Mismo día hábil." },
      { question: "¿Cuál es el horario?", answer: "Lunes a sábado, 8:00 AM a 6:00 PM." },
      { question: "¿Puedo contactar por llamada o SMS?", answer: "Sí, ambos." },
      { question: "¿Cuál es el contacto?", answer: "Teléfono (386) 403-9460. Email info@smoothfenceusa.com." },
    ],
  },
  {
    slug: "services",
    label: "Servicios",
    items: [
      { question: "¿Qué tipos de cerca instalan?", answer: "Instalamos cercas de vinyl, aluminio, chain-link, y madera." },
      { question: "¿Hacen reparación?", answer: "Sí. Reparamos secciones dañadas, postes caídos, paneles rotos, problemas de portones, y algunas cercas dañadas por tormenta." },
      { question: "¿Son personalizables?", answer: "Sí." },
      { question: "¿Qué material funciona mejor en Florida?", answer: "Depende. Vinyl: bajo mantenimiento y privacidad. Aluminio: durabilidad y visibilidad. Chain-link: accesible. Madera: look clásico." },
      { question: "¿Qué estilos de vinyl hay?", answer: "Full privacy, privacy con top decorativo, semi-privacy, y picket." },
      { question: "¿Aluminio para piscina?", answer: "Sí. Seguridad, visibilidad y look limpio." },
      { question: "¿Instalan madera?", answer: "Sí, es una opción estándar." },
      { question: "¿Pueden reparar solo una parte?", answer: "Sí si el daño es puntual. Si es estructural generalizado, conviene reemplazar." },
      { question: "¿Se hacen cargo de daño por tormenta?", answer: "Sí, inspeccionamos y definimos." },
      { question: "¿Retiran la cerca vieja?", answer: "Sí, si hace falta va incluido en la cotización." },
      { question: "¿Matchean la cerca actual?", answer: "A veces, depende de material, estilo, color, antigüedad, y disponibilidad hoy." },
      { question: "¿Qué tipos y tamaños de portón ofrecen?", answer: "Los portones peatonales estándar son de 4 ft y 5 ft de ancho. También fabricamos portones a medida, de cualquier tamaño y material. Los portones custom suman cargos adicionales de fabricación, instalación y transporte." },
      { question: "¿Se pueden automatizar los portones?", answer: "No. Smooth Fence USA no ofrece automatización de portones. Todos son manuales. Si necesitás automatización, se coordina aparte con un instalador de access-control después de que terminamos el portón." },
      { question: "¿Qué herraje usan?", answer: "Bisagras y pestillos heavy-duty, galvanizados o inoxidables, dimensionados para el peso y material de cada portón. No nos casamos con una marca específica; elegimos lo que funcione mejor para cada proyecto. Si tenés preferencia de marca, estamos abiertos a usarla a pedido." },
      { question: "¿Cómo manejan la seguridad de portón para piscina?", answer: "El código de Florida suele exigir hardware self-closing y self-latching, con el pestillo a más de 54 pulgadas del piso, y que el portón abra hacia afuera de la piscina. Instalamos hardware compliant a pedido." },
      { question: "¿Instalan control de acceso (teclados, card readers)?", answer: "Instalamos cerraduras y pestillos manuales. Para teclado, intercom o card reader, el cliente coordina con un proveedor aparte." },
      { question: "¿Los postes van en concreto?", answer: "Depende del proyecto, suelo, código local, y tipo de cerca. Siempre buscando estabilidad y durabilidad." },
      { question: "¿Cómo aguantan las cercas el clima de Florida?", answer: "Elegimos materiales y métodos pensados para calor, humedad, tormentas y zona costera." },
      { question: "¿Qué es virgin vinyl?", answer: "Vinyl nuevo, no reciclado, preferido por consistencia y durabilidad." },
      { question: "Routed vs bracket-mounted — ¿cuál es la diferencia?", answer: "Routed inserta travesaños directo en el poste, look más limpio. Bracket usa conectores externos." },
      { question: "¿Qué post caps hay disponibles?", answer: "Flat, pyramid, gothic, New England, y con luz solar." },
    ],
  },
  {
    slug: "service-area",
    label: "Cobertura y Estimados",
    items: [
      { question: "¿Qué áreas cubren?", answer: "Palm Coast, Flagler County, Volusia County, St. Johns County, Duval County y Putnam County. Zonas cercanas se evalúan caso por caso." },
      { question: "¿Los estimados son gratis?", answer: "Sí, gratuitos y sin compromiso." },
      { question: "¿Cuál es la forma más rápida de cotizar?", answer: "Usando el instant estimator en smoothfenceusa.com/estimator, y después se agenda la visita gratuita para confirmar." },
      { question: "¿Cuánto tarda la instalación?", answer: "La mayoría de proyectos residenciales se completan en 1 a 3 días, según tamaño, terreno, clima, acceso, y material." },
      { question: "¿Qué afecta el precio de una cerca?", answer: "Material, altura, pies lineales, cantidad de portones, terreno, trazado, remoción de cerca vieja, y condiciones especiales del sitio. El precio firme sale solo después de la visita gratuita." },
      { question: "¿Ayudan con HOA?", answer: "Sí, revisamos requisitos y damos info de soporte." },
      { question: "¿Quién presenta la solicitud al HOA?", answer: "Normalmente el homeowner. Nosotros preparamos la info." },
      { question: "¿Los proyectos requieren permisos?", answer: "Algunos proyectos requieren, otros no. Depende de ubicación y alcance. Acompañamos el trámite si hace falta." },
      { question: "¿Cómo manejan líneas de propiedad y easements?", answer: "Las consideramos al planificar, pero la definición final la da el survey o la autoridad." },
      { question: "¿Qué preparar antes del día de instalación?", answer: "Acceso libre, área despejada, mascotas aseguradas, y temas de HOA/permisos encaminados si hacen falta." },
    ],
  },
  {
    slug: "financing",
    label: "Financiamiento y Precios",
    items: [
      { question: "¿Ofrecen financiamiento?", answer: "Sí, a través de Hearth para clientes calificados." },
      { question: "¿Aplicar afecta el score de crédito?", answer: "No, Hearth usa soft-pull." },
      { question: "¿Puedo pagar en cuotas?", answer: "Sí, para quienes califican." },
      { question: "¿Qué tipos de financiamiento hay?", answer: "Personal loans, HELOCs, y tarjetas con promociones." },
      { question: "¿Hay 0% de interés?", answer: "Algunos califican para 0% APR introductorio, según el prestamista." },
      { question: "¿En cuánto salen los fondos?", answer: "En algunos casos en 24 horas una vez aprobado." },
      { question: "¿Cuál es el FICO mínimo?", answer: "Hearth dice que desde 550 suele haber opciones, pero depende del prestamista." },
      { question: "¿Necesito el estimado antes del financiamiento?", answer: "Sí, primero el estimado, después el financiamiento." },
    ],
  },
];
